/**
 * The WebVN script controller <br>
 * Include lexer, javascript eval and a bunch of other things
 * for controlling the scripts.<br>
 * Note: the parser is generated by jison.
 * @namespace webvn.script
 */
webvn.module('script',
    ['parserNew', 'parserNode', 'class', 'util', 'log', 'config', 'loader'],
    function (parser, parserYy, kclass, util, log, config, loader) {



        // Command



        return exports;

    });