webvn.use(function (ui) { ui.template.create({
    "config": "<div class=\"ui-title\"><%= Config %></div>\r\n<ul class=\"container\">\r\n    <li>\r\n        <label><%= Text_Speed %></label>\r\n        <input class=\"range-slider text-speed\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\">\r\n    </li>\r\n    <li>\r\n        <label><%= Text_Auto %></label>\r\n        <input class=\"range-slider\" type=\"range\">\r\n    </li>\r\n    <li>\r\n        <label><%= Music %></label>\r\n        <input class=\"range-slider music\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\">\r\n    </li>\r\n    <li>\r\n        <label><%= Sound %></label>\r\n        <input class=\"range-slider sound\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\">\r\n    </li>\r\n    <li>\r\n        <label><%= Voice %></label>\r\n        <input class=\"range-slider voice\" type=\"range\" min=\"0\" max=\"1\" step=\"0.01\">\r\n    </li>\r\n</ul>\r\n<div class=\"close button\"><%= Close %></div>",
    "console": "",
    "dialog": "<div class=\"wrapper\">\r\n    <div class=\"name\"></div>\r\n    <div class=\"content\">\r\n        <img class=\"face hidden\" src=\"\"/>\r\n        <span class=\"text\"></span>\r\n    </div>\r\n    <ul class=\"controls\">\r\n        <li class=\"qsave\"><%= Q_Save %></li>\r\n        <li class=\"qlave\"><%= Q_Load %></li>\r\n        <li class=\"save\"><%= Save %></li>\r\n        <li class=\"load\"><%= Load %></li>\r\n        <li class=\"config\"><%= Config %></li>\r\n        <li class=\"log\"><%= History %></li>\r\n        <li class=\"exit\"><%= Title %></li>\r\n    </ul>\r\n</div>",
    "gallery": "<div class=\"ui-title\"><%= Gallery %></div>\r\n<ul class=\"container\">\r\n</ul>\r\n<ul class=\"pagination\">\r\n    <% if (pageCount > 1) {%>\r\n        <% for (var i = 0; i < pageCount; i++) { %>\r\n            <li class=\"button\" data-num=\"<%= i + 1 %>\"><%= i + 1 %></li>\r\n        <% } %>\r\n    <% } %>\r\n</ul>\r\n<div class=\"close button\"><%= Close %></div>\r\n<div class=\"viewer fill hidden\">\r\n    <img class=\"fore\" src=\"\" />\r\n    <img class=\"back\" src=\"\" />\r\n</div>\r\n",
    "gallery_image": "<% util.each(images, function (image, idx) { %>\r\n<li>\r\n    <% if (image.collected[0]) { %>\r\n    <img class=\"th\" src=\"<%= image.src[0] %>\" data-num=\"<%= idx %>\">\r\n    <% } else { %>\r\n    <img class=\"th\" src=\"engine/img/blank.gif\">\r\n    <% } %>\r\n    </li>\r\n<% }); %>",
    "menu": "<ul>\r\n    <li class=\"start\"><%= Start %></li>\r\n    <li class=\"load\"><%= Load %></li>\r\n    <li class=\"cg\"><%= Gallery %></li>\r\n    <li class=\"music\"><%= Music %></li>\r\n    <li class=\"setting\"><%= Config %></li>\r\n</ul>",
    "music": "<div class=\"ui-title\"><%= Music %></div>\r\n<ul class=\"container\">\r\n</ul>\r\n<div class=\"progress\">\r\n    <span></span>\r\n</div>\r\n<div class=\"close button\"><%= Close %></div>\r\n<ul class=\"controls\">\r\n    <li class=\"previous button disabled\">&lt;&lt;</li>\r\n    <li class=\"play button disabled\"><%= Play %></li>\r\n    <li class=\"next button disabled\">&gt;&gt;</li>\r\n</ul>",
    "save": "<div class=\"ui-title\"><%= Title %></div>\r\n<ul class=\"container\">\r\n    <% util.each(records, function (record, index) { %>\r\n        <li class=\"<%= type %>\" data-num=\"<%= index %>\">\r\n            <span>\r\n                <%= record.title %><br><br>\r\n                <%= record.date %>\r\n            </span>\r\n        </li>\r\n    <% }) %>\r\n</ul>\r\n<div class=\"close button\"><%= Close %></div>\r\n",
    "video": "<video class=\"fill\"></video>"
});});